name: Manager

on: push

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: "cd server && cd web && npm install"
      - run: "cd server && npm serve"
