on : push
jobs : 
  build-node : 
    runs-on : ubuntu-latest
    container : node:14
    steps : 
      - run : node --version
      - run : npm --version
      - uses : actions/checkout@v3
      - run : cd serve && cd web && npm install
      - run : cd serve && npm run serve